name: Build Windows Executables
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests pywin32 pyinstaller-hooks-contrib
    - name: Build executables
      shell: pwsh
      working-directory: Client/Windows
      run: |
        Write-Host "Cleaning previous builds..."
        Remove-Item -Recurse -Force -ErrorAction SilentlyContinue build, dist
        Write-Host "Building power_monitor.exe..."
        pyinstaller --clean power_monitor.spec
        if (-not (Test-Path "dist/power_monitor.exe")) {
            Write-Error "Failed to build power_monitor.exe"
            exit 1
        }
        Write-Host "Building AttendanceTracker.exe..."
        pyinstaller --clean AttendanceTracker.spec
        if (-not (Test-Path "dist/AttendanceTracker.exe")) {
            Write-Error "Failed to build AttendanceTracker.exe"
            exit 1
        }
        Write-Host "Contents of dist directory:"
        Get-ChildItem "dist" | Format-Table Name, Length
    - name: Create distribution package
      shell: pwsh
      run: |
        Write-Host "Creating final package..."
        New-Item -ItemType Directory -Path "package_win" -Force
        Write-Host "Copying files..."
        Copy-Item "Client/Windows/dist/power_monitor.exe" "package_win/" -Force
        Copy-Item "Client/Windows/dist/AttendanceTracker.exe" "package_win/" -Force
        Copy-Item "Client/Windows/config.json" "package_win/" -Force
        Copy-Item "Client/Windows/test_install.bat" "package_win/" -Force
        Copy-Item "Client/Windows/uninstall.bat" "package_win/" -Force
        Copy-Item "Client/Windows/start.bat" "package_win/" -Force
        Write-Host "Final package contents:"
        Get-ChildItem "package_win" | Format-Table Name, Length
        Write-Host "Zipping package..."
        Compress-Archive -Path "package_win/*" -DestinationPath "AttendanceTracker_Windows_x64.zip" -Force
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AttendanceTracker-Windows-x64
        path: AttendanceTracker_Windows_x64.zip