name: Build Windows Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest  # This ensures we get a 64-bit Windows environment

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'  # Explicitly request 64-bit Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --use-pep517 requests pywin32 pyinstaller-hooks-contrib

    - name: Build executables
      shell: pwsh  # Explicitly use PowerShell
      run: |
        Set-Location Client\Windows
        if (-not (Test-Path "dist")) {
            New-Item -ItemType Directory -Path "dist"
        }
        pyinstaller power_monitor.spec
        if (-not (Test-Path "dist\power_monitor.exe")) {
            Write-Error "Failed to build power_monitor.exe"
            exit 1
        }
        pyinstaller AttendanceTracker.spec
        if (-not (Test-Path "dist\AttendanceTracker.exe")) {
            Write-Error "Failed to build AttendanceTracker.exe"
            exit 1
        }
        Set-Location ..\..

    - name: Prepare package
      shell: pwsh  # Explicitly use PowerShell
      run: |
        if (-not (Test-Path "distwin")) {
            New-Item -ItemType Directory -Path "distwin"
        }
        if (-not (Test-Path "distwin\package")) {
            New-Item -ItemType Directory -Path "distwin\package"
        }
        
        Write-Host "Copying files to package directory..."
        Copy-Item "Client\Windows\dist\power_monitor.exe" "distwin\package\" -Force
        if (-not $?) {
            Write-Error "Failed to copy power_monitor.exe"
            exit 1
        }
        Copy-Item "Client\Windows\dist\AttendanceTracker.exe" "distwin\package\" -Force
        if (-not $?) {
            Write-Error "Failed to copy AttendanceTracker.exe"
            exit 1
        }
        Copy-Item "Client\Windows\config.json" "distwin\package\" -Force
        Copy-Item "Client\Windows\test_install.bat" "distwin\package\" -Force
        Copy-Item "Client\Windows\uninstall.bat" "distwin\package\" -Force
        Copy-Item "Client\Windows\start.bat" "distwin\package\" -Force

    - name: Create ZIP archive
      shell: pwsh  # Using PowerShell for better ZIP handling
      run: |
        Set-Location distwin
        Compress-Archive -Path "package\*" -DestinationPath "AttendanceTracker_Windows.zip" -Force
        if (-not (Test-Path "AttendanceTracker_Windows.zip")) {
            Write-Error "Failed to create ZIP file"
            exit 1
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AttendanceTracker-Windows-x64
        path: distwin/AttendanceTracker_Windows.zip