name: Build Windows Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest  # This ensures we get a 64-bit Windows environment

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'  # Explicitly request 64-bit Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --use-pep517 requests pywin32 pyinstaller-hooks-contrib

    - name: Build executables
      shell: pwsh  # Explicitly use PowerShell
      run: |
        Set-Location Client\Windows
        Write-Host "Building power_monitor.exe..."
        pyinstaller power_monitor.spec
        if (-not (Test-Path "dist\power_monitor.exe")) {
            Write-Error "Failed to build power_monitor.exe"
            exit 1
        }
        
        Write-Host "Building AttendanceTracker.exe..."
        pyinstaller AttendanceTracker.spec
        if (-not (Test-Path "dist\AttendanceTracker.exe")) {
            Write-Error "Failed to build AttendanceTracker.exe"
            exit 1
        }
        Set-Location ..\..

    - name: Create distribution package
      shell: pwsh  # Explicitly use PowerShell
      run: |
        Write-Host "Creating distribution package..."
        
        # Create a clean directory for the package
        New-Item -ItemType Directory -Path "dist" -Force
        
        Write-Host "Copying executables..."
        Copy-Item "Client\Windows\dist\power_monitor.exe" "dist\" -Force
        Copy-Item "Client\Windows\dist\AttendanceTracker.exe" "dist\" -Force
        
        Write-Host "Copying support files..."
        Copy-Item "Client\Windows\config.json" "dist\" -Force
        Copy-Item "Client\Windows\test_install.bat" "dist\" -Force
        Copy-Item "Client\Windows\uninstall.bat" "dist\" -Force
        Copy-Item "Client\Windows\start.bat" "dist\" -Force
        
        Write-Host "Creating ZIP archive..."
        Compress-Archive -Path "dist\*" -DestinationPath "AttendanceTracker_Windows.zip" -Force
        
        Write-Host "Package contents:"
        Get-ChildItem "dist" | Format-Table Name, Length
        
        Write-Host "Final ZIP file size:"
        Get-Item "AttendanceTracker_Windows.zip" | Format-Table Name, Length

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AttendanceTracker-Windows-x64
        path: AttendanceTracker_Windows.zip